name: Showcase
markdown: kramdown
plugins:
  - jekyll-coffeescript
sass:
  style: compressed
exclude:
  - _scripts
  - _coffee
  - _junk
  - node_modules
  - package.json
  - CNAME
  - README.md
  - _data/Readme.md
  - _sass/Readme.md
  - docs
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
